var svg = d3.select(".area_title")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 150)
    .attr('transform','translate(180,0)')

    svg.append('text')
    .attr('x', 250)
    .attr('y', 70)
    .text('< Top 3 Lowest Arrest Rate Area >')
    .style('font-size', '19px')
    .attr("font-family", "sans-serif")
    .attr("fill", "black")

    svg.append('text')
    .attr('x', 100)
    .attr('y', 130)
    .text('# Annual Top 3 #')
    .style('font-size', '19px')
    .attr("font-family", "sans-serif")
    .attr("fill", "black")

    svg.append('text')
    .attr('x', 650)
    .attr('y', 130)
    .text('# Total #')
    .style('font-size', '19px')
    .attr("font-family", "sans-serif")
    .attr("fill", "black")