var svg = d3.select(".it")
    .append("svg")
    .attr('width', 800)
    .attr('height', 40)
    .attr('transform', 'translate(-7,-10)')

svg.append('text')
    .attr('x', 0)
    .attr('y', 30)
    .text("2009")
    .style('font-size', '11px')
    .attr("font-family", "sans-serif")
    .attr("fill", "gray")

svg.append('text')
    .attr('x', 67)
    .attr('y', 30)
    .text("2014")
    .style('font-size', '11px')
    .attr("font-family", "sans-serif")
    .attr("fill", "gray")

svg.append('text')
    .attr('x', 120)
    .attr('y', 30)
    .text("2018")
    .style('font-size', '11px')
    .attr("font-family", "sans-serif")
    .attr("fill", "gray")

svg.append('line')
    .attr('x1', 15)
    .attr('y1', 5)
    .attr('x2', 15)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

svg.append('line')
    .attr('x1', 27)
    .attr('y1', 5)
    .attr('x2', 27)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

svg.append('line')
    .attr('x1', 40)
    .attr('y1', 5)
    .attr('x2', 40)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

svg.append('line')
    .attr('x1', 53)
    .attr('y1', 5)
    .attr('x2', 53)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

svg.append('line')
    .attr('x1', 66)
    .attr('y1', 5)
    .attr('x2', 66)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

svg.append('line')
    .attr('x1', 80)
    .attr('y1', 5)
    .attr('x2', 80)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

svg.append('line')
    .attr('x1', 93)
    .attr('y1', 5)
    .attr('x2', 93)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

svg.append('line')
    .attr('x1', 105)
    .attr('y1', 5)
    .attr('x2', 105)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

svg.append('line')
    .attr('x1', 118)
    .attr('y1', 5)
    .attr('x2', 118)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

svg.append('line')
    .attr('x1', 131)
    .attr('y1', 5)
    .attr('x2', 131)
    .attr('y2', 10)
    .style('stroke', 'black')
    .style('stroke-width', 0.6)

    svg.append('text')
    .attr('x', 500)
    .attr('y', 20)
    .text("< Annual Data >")
    .style('font-size', '18px')
    .attr("font-family", "sans-serif")
    .attr("fill", "black")