var svg = d3.select(".area_title")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 150)
    .attr('transform','translate(180,0)')

    svg.append('text')
        .attr('x', 200)
        .attr('y', 130)
        .text('< Number of crimes by type >')
        .style('font-size', '19px')
        .attr("font-weight", "bold")
        .attr("font-family", "sans-serif")
        .attr("fill", "black")
