var svg = d3.select(".crime_type_title")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 40)
    .attr('transform','translate(180,0)')

    svg.append('text')
        .attr('x', 400)
        .attr('y', 30)
        .text('[Crime Type Tree]')
        .style('font-size', '20px')
        .attr("font-family", "sans-serif")
        .attr("fill", "black")
        .style('font-weight', 'bold')
