var svg = d3.select(".line_title")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 50)
    .attr('transform','translate(180,0)')

    svg.append('text')
    .attr('x', 350)
    .attr('y', 40)
    .text('[Check Rate Heinrich\'s law]')
    .style('font-size', '20px')
    .style('font-weight', 'bold')
    .attr("font-family", "sans-serif")
    .attr("fill", "black")
