var svg = d3.select(".pie_title")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 60)
    .attr('transform','translate(180,0)')

    svg.append('text')
    .attr('x', 200)
    .attr('y', 30)
    .text('[Arrested Crime Ratio]')
    .style('font-weight', 'bold')
    .style('font-size', '20px')
    .attr("font-family", "sans-serif")
    .attr("fill", "black")
